version: '3.8'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: on-failure
    depends_on:
      - db
    volumes:
      - .:/server/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db/postgres
volumes:
  postgres-data:
