"""added_expense_kind

Revision ID: 35d1efa2b918
Revises: f3e412e688a3
Create Date: 2023-05-11 13:31:52.149448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d1efa2b918'
down_revision = 'f3e412e688a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('expenseKind', sa.Enum('Need', 'Want', name='expensekind'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'expenseKind')
    # ### end Alembic commands ###
